/*
 * To change this license header, choose License Headers CrearNuevoUsuario Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template CrearNuevoUsuario the editor.
 */
package frames;

import clases.conectar;
import clases.ListaVenta;
import java.awt.TextField;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

public class ventanaLogin_1 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ventanaVendedor_1 VV;
    private ventanaAdministrador_1 VA;
    private ListaVenta Venta = new ListaVenta();

    public ListaVenta getVenta() {
        return Venta;
    }

    public void setVenta(ListaVenta Venta) {
        this.Venta = Venta;
    }

    public ventanaVendedor_1 getVV() {
        return VV;
    }

    public void setVV(ventanaVendedor_1 VSDC) {
        this.VV = VSDC;
    }

    public ventanaAdministrador_1 getVA() {
        return VA;
    }

    public void setVA(ventanaAdministrador_1 VA) {
        this.VA = VA;
    }
    
    public ventanaLogin_1() {
        initComponents();
        

        ((JPanel) getContentPane()).setOpaque(false);
        
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/imagenes/Fondo.JPG"));
        
        // Definimos fondo de JLabel
        // En el JLabel es donde vamos agregar la imagen como fondo
        JLabel fondo = new JLabel();

        // Habilitamos la opcion de Icon
        fondo.setIcon(uno);

        // Aqui habilitamos el getLayeredPanel
        // Es para poder agregar el fondo que nosotros queramos poner
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);

        // Esta funcion es para poner el tamano de los bordes ya sea el ancho o el largo
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());

        // Para localizarlo en el centro de la pantalla de la computadora
        setLocationRelativeTo(this);

        // Desabilitar el maximizado del frame
        this.setResizable(false);

        // Habilitamos el titulo encima del frame
        this.setTitle("Sistema de Cafeteria");

        // El campo del usuario cuando se inicia el sistema va a estar el campo vacio
        txtUsuario.setText("");

        // El campo de la contrasena cuando se inicia el sistema va a estar el campo vacio
        txtContrasena.setText("");
        
        VA = null;
        VV = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoginDelUsuario = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new java.awt.TextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLoginDelUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lblLoginDelUsuario.setForeground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        lblUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblContrasena.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña:");

        jLayeredPane1.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblContrasena, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtContrasena, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addComponent(txtContrasena))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btnAnterior.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Anterior.png"))); // NOI18N
        btnAnterior.setText("ANTERIOR");
        btnAnterior.setBorderPainted(false);
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAnterior)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 701, Short.MAX_VALUE)
                .addComponent(lblLoginDelUsuario)
                .addContainerGap(651, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblLoginDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAnterior))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        
        // Llamamos a la ventana anterior "Administrador Politicas"
        
        // Hacemos visible la ventana "Administrador Politicas"
    
        
        // Realizamos a la funcion "dispose" de la ventana actual
        
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        String usuario = this.txtUsuario.getText();
        String contrasena = this.txtContrasena.getText();
        if(!usuario.equals("") && !contrasena.equals("")){
            conectar cc = new conectar();
            Connection cn = cc.conexion();
            String sql = "";
            sql = "SELECT * FROM usuarios WHERE (usuario='" + usuario + "'  AND contrasena='" + contrasena + "')";
            String[] datos = new String[3];
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    datos[0] = rs.getString(1);
                    datos[1] = rs.getString(2);
                    datos[2] = rs.getString(3);
                }
                if(datos[2] != null){
                    if(datos[2].equals("Administrador")){
                        this.setVA(new ventanaAdministrador_1());
                        this.getVA().setVisible(true);
                        dispose();
                    }else{
                        if(datos[2].equals("Vendedor")){
                            this.setVV(new ventanaVendedor_1());
                            this.getVV().setVisible(true);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Imposible ingresar");
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro o no esta escrito correctamente");
                }
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese una contrasena");
        }
        

    
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced CrearNuevoUsuario Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblLoginDelUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContrasena;
    private java.awt.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables


}
