/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.ListaVenta;
import java.awt.TextField;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dannycolumna
 */


public class ventanaFacturaVendedor_1 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
     private ListaVenta Venta;

    public ListaVenta getVenta() {
        return Venta;
    }

    public void setVenta(ListaVenta proceso) {
        this.Venta = proceso;
    }
    
    public ventanaFacturaVendedor_1() {
        initComponents();
        
        // Llamamos al contenedor del Frame
        // La funion de ser opaco va a estar desabilitada
        ((JPanel) getContentPane()).setOpaque(false);
        
        // Definimos uno de ImageIcon
        // En el getResource vamos a poner la ubicacion exacta de la imagen que queramos utilizar
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/imagenes/Fondo.JPG"));
        
        // Definimos fondo de JLabel
        // En el JLabel es donde vamos agregar la imagen como fondo
        JLabel fondo = new JLabel();
        
        // Habilitamos la opcion de Icon
        fondo.setIcon(uno);
        
        // Aqui habilitamos el getLayeredPanel
        // Es para poder agregar el fondo que nosotros queramos poner
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        
        // Esta funcion es para poner el tamano de los bordes ya sea el ancho o el largo
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
        
        // Para localizarlo en el centro de la pantalla de la computadora
        setLocationRelativeTo(this);
        
        // Desabilitar el maximizado del frame
        this.setResizable(false);
        
        // Habilitamos el titulo encima del frama
        this.setTitle("Sistema de Cafeteria");
        
        this.setVenta(clases.main.V.getVV().getVenta());
        
        this.MostrarProductos();
        
        this.MostrarPrecio();
    }
    
    private void MostrarProductos(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Precio");
        if(Venta != null){
            String[] datos = new String[2];
            if(this.getVenta().getCabeza().getBebida().getLista().getCabeza() != null){
                for(int i = 0; i < this.getVenta().size(); i++){
                    datos[0] = "Bebida";
                    datos[1] =  Integer.toString(i+1);
                    modelo.addRow(datos);
                    for(int j = 0; j < this.getVenta().get(i).Tamano(); j++){
                        datos[0] = this.getVenta().get(i).obtener(j).getNombre();
                        datos[1] = Integer.toString(this.getVenta().get(i).obtener(j).getPrecio());
                        modelo.addRow(datos);
                    }
                    datos[0] = " ";
                    datos[1] = " ";
                    modelo.addRow(datos);
                } 
            }  
        }  
        jTable1.setModel(modelo);
    }
    
    private void MostrarPrecio(){
        int precio = 0;
        for(int i = 0; i < this.getVenta().size(); i++){
            precio += this.getVenta().get(i).PrecioTotal();
        }
        jTextField1.setText(Integer.toString(precio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPoliticasDeLaEmpresa = new javax.swing.JLabel();
        btnSalirDelSistema = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btnCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPoliticasDeLaEmpresa.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lblPoliticasDeLaEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblPoliticasDeLaEmpresa.setText("FACTURA");

        btnSalirDelSistema.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnSalirDelSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirDelSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        btnSalirDelSistema.setText("SALIR DEL SISTEMA");
        btnSalirDelSistema.setBorderPainted(false);
        btnSalirDelSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirDelSistemaActionPerformed(evt);
            }
        });

        btnAnterior.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Anterior.png"))); // NOI18N
        btnAnterior.setText("ANTERIOR");
        btnAnterior.setBorderPainted(false);
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnCompra.setText("Confirmar Compra");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        jLabel1.setText("Precio Final");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(btnCompra)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnCompra)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalirDelSistema)
                    .addComponent(btnAnterior))
                .addContainerGap(1404, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPoliticasDeLaEmpresa)
                        .addGap(538, 538, 538))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnSalirDelSistema)
                .addGap(12, 12, 12)
                .addComponent(lblPoliticasDeLaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnterior))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirDelSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirDelSistemaActionPerformed
        // TODO add your handling code here:
        
        // Se inicializa respuesta que es igual a un mensaje de error
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        
        // Si la respuesta es igual al mensaje de error de la opcion "si"
        if (respuesta == JOptionPane.YES_OPTION) {
            
            // Si pasa esto
            try {
                
                // Esta ventana se cierra
                this.dispose();
                
                // Si no pasa lo anterior, esto es lo que va a suceder
            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_btnSalirDelSistemaActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
       
       // Llamamos a la ventana anterior "Vendedor"
       ventanaVendedor_1 VV = new ventanaVendedor_1();
       
       // Hacemos visble la ventana "Vendedor"
       VV.setVisible(true);
       
       // Realizamos la funcion "dispose" de la ventana actual
       this.dispose();
       
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        if(jTextField1.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "No hay compra que realizar");
        }else{
            JOptionPane.showMessageDialog(null, "Compra realizada");
            this.dispose();
        }
    }//GEN-LAST:event_btnCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaFacturaVendedor_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaFacturaVendedor_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaFacturaVendedor_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaFacturaVendedor_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaFacturaVendedor_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnSalirDelSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPoliticasDeLaEmpresa;
    // End of variables declaration//GEN-END:variables
}
